/**
 * AI 向け tests.yml 生成プロンプト。
 * HomePage の「コピー」ボタンでそのままクリップボードへ渡す。
 */
export const TESTS_YAML_AI_GUIDE = `# qarows tests.yml specification

Generate a valid \`tests.yml\` file for qarows (QA test runner).
Output YAML only — no markdown fences, no commentary before or after the file.

## Purpose

- \`tests.yml\` defines test cases, environments (devices/browsers), and optional grouping rules.
- Execution results are stored separately in \`results.json\` (generated by qarows). Do NOT include results in tests.yml.

## Root object (required keys)

\`\`\`yaml
project:        # required
environments:   # required, non-empty array
testCases:      # required, non-empty array
categoryTargets: # optional array
scenarios:      # optional array
\`\`\`

## project (required)

| field | type | required | notes |
|---|---|---|---|
| name | string | yes | display name, non-empty |
| id | string | no | stable slug; auto-generated from name if omitted |
| version | number | no | default 1 |

## environments (required, ≥1)

Each item:
- \`id\` (string, unique, non-empty) — referenced by categoryTargets / targetEnvironments
- \`name\` (string) — display label; defaults to id

Shorthand: a bare string is treated as both id and name.

## testCases (required, ≥1)

Each item:

| field | type | required | notes |
|---|---|---|---|
| id | string | yes | unique across file (e.g. TC-001) |
| version | number | no | test definition revision; default 1; omit when 1. Bump when content changes; stale results become incomplete |
| description | string | yes | what to verify (shown prominently in runner) |
| category.major | string | yes | top-level grouping / filter |
| category.medium | string | no | mid-level grouping |
| category.minor | string | no | fine grouping |
| prerequisites | string | no | preconditions before running |
| targetEnvironments | object | no | per-case override (see below) |

## targetEnvironments / categoryTargets spec

Both use the same shape:

\`\`\`yaml
required: all   # "all" | "any" — completion rule; default "all"
targets:        # optional string[] of environment ids
  - chrome-desktop
\`\`\`

### required

- \`all\`: every in-scope environment must have a result before the case is "complete"
- \`any\`: one result in any in-scope environment completes the case

### targets

- omitted → use current effective pool (all environments, narrowed by parent rules)
- specified → effective pool = intersection with listed ids

### Resolution order (narrowing only — cannot widen)

1. Start with all \`environments\`
2. Apply matching \`categoryTargets\` in order: major only → major+medium → major+medium+minor
3. Apply case \`targetEnvironments\` last
4. At each step: intersect \`targets\` if present; overwrite \`required\` if present

At runtime, the session's selected environments are intersected again.

## categoryTargets (optional)

\`\`\`yaml
categoryTargets:
  - match:
      major: "認証"           # required in match
      medium: "ログイン"      # optional
      minor: "OAuth"          # optional
    required: all             # optional
    targets:                  # optional
      - chrome-desktop
\`\`\`

Use to set default required/targets for a category subtree without repeating on every case.

## scenarios (optional)

Predefined ordered test runs (filter mode alternative in UI).

\`\`\`yaml
scenarios:
  - id: smoke                 # required, unique
    name: "スモーク"           # required
    description: |            # optional
      Short explanation.
    steps:                    # required, ≥1 testCase id
      - TC-001
      - TC-002
\`\`\`

Every \`steps\` entry must reference an existing \`testCases[].id\`.

## Validation rules (must satisfy)

- Root must be a YAML object
- All ids unique within their collection (environment id, testCase id, scenario id)
- \`targets\` ids must exist in \`environments\`
- No empty strings for required fields
- Do not change existing testCase ids when updating a file (breaks saved results)

## Authoring tips for AI

- Prefer stable ids: TC-001, TC-002, … or feature-prefixed ids
- Group by \`category.major\` aligned with product features
- Write \`description\` as a concrete, testable observation (not "check login")
- Put shared environment rules in \`categoryTargets\`; override only exceptions on cases
- Use \`required: all\` unless the case genuinely needs only one environment (\`any\`)
- Add \`scenarios\` for common QA flows (smoke, regression, release checklist)
- Keep \`prerequisites\` short: screen, data state, role, feature flags

## Minimal valid example

project:
  name: "My App QA"
  id: my-app-qa
  version: 1

environments:
  - id: chrome-desktop
    name: "Chrome (Desktop)"
  - id: ios-safari
    name: "iOS Safari"

categoryTargets:
  - match:
      major: "認証"
    required: all

testCases:
  - id: TC-001
    category:
      major: "認証"
      medium: "ログイン"
    prerequisites: "未ログイン状態"
    description: "正しいメールとパスワードでログインできる"

  - id: TC-002
    category:
      major: "認証"
      medium: "ログイン"
    prerequisites: "未ログイン状態"
    description: "誤ったパスワードではログインできない"

## Task template (fill in for the user)

Create tests.yml for: <PROJECT_NAME>
Environments to include: <LIST>
Major feature areas: <LIST>
Additional constraints: <ANY>
`;
