/** AI 向け tests.yml 生成プロンプト。TestsYamlGuide のコピー用。 */
export const TESTS_YAML_AI_GUIDE = `# qarows tests.yml specification

Generate a valid \`tests.yml\` file for qarows (QA test runner).
Output YAML only — no markdown fences, no commentary before or after the file.

## Purpose

- \`tests.yml\` defines test cases, environments (devices/browsers), and optional grouping rules.
- Execution results are stored separately in \`results.json\` (generated by qarows). Do NOT include results in tests.yml.

## Root object (required keys)

\`\`\`yaml
project:        # required
environments:   # required, non-empty array
testCases:      # required, non-empty array
categoryTargets: # optional array
scenarios:      # optional array
\`\`\`

## project (required)

| field | type | required | notes |
|---|---|---|---|
| name | string | yes | display name, non-empty |
| id | string | no | stable slug; auto-generated from name if omitted |
| version | number | no | default 1 |

## environments (required, ≥1)

Each item:
- \`id\` (string, unique, non-empty) — referenced by categoryTargets / targetEnvironments
- \`name\` (string) — display label; defaults to id

Shorthand: a bare string is treated as both id and name.

## testCases (required, ≥1)

Each item:

| field | type | required | notes |
|---|---|---|---|
| id | string | yes | unique across file (e.g. TC-001) |
| version | number | no | test definition revision; default 1; omit when 1. Bump when content changes; stale results become incomplete |
| description | string | yes | what to verify (shown prominently in runner) |
| category.major | string | yes | top-level grouping / filter |
| category.medium | string | no | mid-level grouping |
| category.minor | string | no | fine grouping |
| prerequisites | string | no | preconditions before running |
| targetEnvironments | object | no | per-case override (see below) |

## Task template (fill in for the user)

Create tests.yml for: <PROJECT_NAME>
Environments to include: <LIST>
Major feature areas: <LIST>
Additional constraints: <ANY>
`;
